#!/bin/bash

# Scott Wales 20190522

print_help() {
cat <<EOF
Run a Jupyter notebook on Gadi's compute nodes, presenting the interface in a
browser on the local machine

General Options:
    -h:         Print help
    -l:         NCI username
    -L:         NCI login node (default 'gadi.nci.org.au')
    -e:         Conda environment
    -d:         Debug mode

Queue Options:
    -q QUEUE:   Queue name
    -n NCPU:    Use NCPU cpus
    -m MEM:     Memory allocation (default 4*NCPU GB)
    -t TIME:    Walltime limit (default 1 hour)
    -J JOBFS:   Jobfs allocation (default 100 GB)
    -P PROJ:    Submit job under project PROJ

EOF
}

set -eu

# Internal defaults
USER=''
PROJECT=''
LOGINNODE='gadi.nci.org.au'
QUEUE='normal'
NCPUS='1'
MEM=''
WALLTIME=1:00:00
JOBFS=100gb
CONDA_ENV=analysis3-20.04
DEBUG=""

# Handle arguments
optspec="hl:L:q:n:m:t:J:P:e:d"
while getopts "$optspec" optchar; do
    case "${optchar}" in
        h)
            print_help
            exit 2
            ;;
        l)
            USER="${OPTARG}"
            ;;
        L)
            LOGINNODE="${OPTARG}"
            ;;
        q)
            QUEUE="${OPTARG}"
            ;;
        n)
            NCPUS="${OPTARG}"
            ;;
        m)
            MEM="${OPTARG}"
            ;;
        t)
            WALLTIME="${OPTARG}"
            ;;
        J)
            JOBFS="${OPTARG}"
            ;;
        P)
            PROJECT="${OPTARG}"
            ;;
        e)
            CONDA_ENV="${OPTARG}"
            ;;
        d)
            DEBUG=true
            ;;
        *)
            print_help
            exit 2
            ;;
    esac
done

# This gets evaluated on Gadi in the SSH script
WORKDIR=/scratch/${PROJECT:-\$PROJECT}/\$USER/tmp/runjp

SSH='ssh -oBatchMode=yes'
if [ -n "$USER" ]; then
    SSH="${SSH} -l ${USER}"
fi
if [ -z "$MEM" ]; then
    MEM="$(( NCPUS * 4 ))gb"
fi

if [ $NCPUS -gt 48 ]; then
    echo "WARNING: Using more than one node with Dask needs extra setup and is not supported by this script"
fi

SUBMITOPTS="-N jupyter-notebook ${PROJECT:+-P '$PROJECT'} -q '$QUEUE' -l 'ncpus=${NCPUS},mem=${MEM},walltime=${WALLTIME},jobfs=${JOBFS}'"

echo "Starting notebook on ${LOGINNODE}..."

# Check connection
$SSH "$LOGINNODE" true

echo "qsub ${SUBMITOPTS}"

# Kill the job if this top-level script is cancelled while the job is still in the queue
trap "{ echo 'Stopping queued job... (Ctrl-C will leave job in the queue)' ; $SSH \"$LOGINNODE\" > /dev/null <<< 'qdel \$(cat $WORKDIR/jobid)' ; }" EXIT

message=$(
$SSH -q "$LOGINNODE" <<EOF | tail -n 1

set -eu

WORKDIR="$WORKDIR"
mkdir -p "\$WORKDIR"

# Check if already running
if [ -f "\$WORKDIR/jobid" ] && qstat \$(cat "\$WORKDIR/jobid") &> /dev/null; then
    while [ ! -f "\$WORKDIR/message" ]; do
        sleep 5
    done
    cat "\$WORKDIR/message"
    exit
fi

rm -f "\$WORKDIR/message"

cat > "\$WORKDIR/runjp.sh" <<EOQ
#!/bin/bash

module purge

eval "\\\$(/g/data/hh5/public/apps/miniconda3/bin/conda shell.bash hook)"
conda activate "${CONDA_ENV}"

set -eu

# Jupyter security token
TOKEN=\\\$(uuidgen)

# Find a remote port https://unix.stackexchange.com/a/132524
PORT=\\\$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')

# Write message file with info for the local connection
echo "\\\$HOSTNAME \\\$TOKEN \\\$PBS_JOBID \\\$PORT" > "\$WORKDIR/message"

echo "runjp log dir \$WORKDIR"
cat "\$WORKDIR/message"

export DASK_LABEXTENSION__FACTORY__MODULE=dask.distributed
export DASK_LABEXTENSION__FACTORY__CLASS=LocalCluster
export DASK_LABEXTENSION__FACTORY__KWARGS__MEMORY_LIMIT=3900MB
export DASK_LABEXTENSION__FACTORY__KWARGS__LOCAL_DIRECTORY=\\\$PBS_JOBFS/dask-worker-space
export DASK_LABEXTENSION__DEFAULT__WORKERS=\\\$PBS_NCPUS
export DASK_DISTRIBUTED__DASHBOARD__LINK="/proxy/{port}/status"

jupyter notebook --NotebookApp.token="\\\$TOKEN" --no-browser --ip="\\\$HOSTNAME" --port "\\\$PORT" --port-retries=0
EOQ

storage="gdata/hh5"
for p in \$(id -nG); do
    if [ \$p = "access.dev" ]; then continue; fi
    if [ \$p = "access.admin" ]; then continue; fi
    if [ -d "/scratch/\$p" ]; then storage="scratch/\$p+\$storage"; fi
    if [ -d "/g/data/\$p" ]; then storage="gdata/\$p+\$storage"; fi
done

qsub $SUBMITOPTS -l "storage=\$storage" -j oe -o "\$WORKDIR/pbs.log" "\$WORKDIR/runjp.sh" > "\$WORKDIR/jobid"

# Wait for the message file to appear, then return to the local process
while [ ! -f "\$WORKDIR/message" ]; do
    sleep 5
done
cat "\$WORKDIR/message"
EOF
)

if [ -n "$DEBUG" ]; then
    echo "DEBUG: Remote Message: '$message'"
fi

# Grab info from the PBS job
read jobhost token jobid remote_port <<< "$message"

# Find a local port
for local_port in {8888..9000}; do
    if ! echo > /dev/tcp/127.0.0.1/${local_port} ; then
        break
    fi 2> /dev/null
done

echo
echo "Notebook running as PBS job ${jobid}"
echo
echo "Starting tunnel..."
if [ -n "$DEBUG" ]; then
    echo "DEBUG:" $SSH -N -L "${local_port}:$jobhost:${remote_port}" "$LOGINNODE"
fi
$SSH -N -L "${local_port}:$jobhost:${remote_port}" "$LOGINNODE" &
tunnelid=$!

# Shut everything down on exit
trap "{ echo 'Closing connections... (Ctrl-C will leave job in the queue)' ; kill $tunnelid ; $SSH "$LOGINNODE" qdel $jobid ; }" EXIT

# Wait for startup then open a browser
sleep 5
URL="http://localhost:${local_port}/lab?token=${token}"

cat << EOF

Start a Dask cluster in your notebook using the Dask panel of Jupyterlab, or by
running (needs kernel analysis3-20.01 or later):

---------------------------------------------------------------
import climtas.nci

climtas.nci.GadiClient()
---------------------------------------------------------------

Opening ${URL}
EOF

set +e
if which xdg-open > /dev/null; then
    xdg-open "$URL"
elif which open > /dev/null; then
    open "$URL"
elif which explorer > /dev/null; then
    explorer "$URL"
else
    echo
    echo "----"
    echo "Notebook available at $URL"
fi
set -e

# Keep open as long as the tunnel exists
wait "$tunnelid"
