#!/bin/bash

set -eu

storage="gdata/hh5"
for p in $(id -nG); do
    if [ $p = "access.dev" ]; then continue; fi
    if [ $p = "access.admin" ]; then continue; fi
    if [ -d "/scratch/$p" ]; then storage="scratch/$p+$storage"; fi
    if [ -d "/g/data/$p" ]; then storage="gdata/$p+$storage"; fi
done

qsub -l storage=$storage "$@"
